# Generated by Django 3.2.16 on 2024-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название контента', max_length=200, unique=True, verbose_name='Название контента')),
                ('platform', models.CharField(help_text='Введите название платформы', max_length=200, verbose_name='Название платформы')),
                ('link', models.URLField(help_text='Введите ссылку на контент', verbose_name='Ссылка')),
                ('guide', models.BooleanField(help_text='Введите руководство', verbose_name='Руководство')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('status', models.CharField(choices=[('IN PROGRESS', 'В работе'), ('PAUSE', 'Пауза'), ('DONE', 'Закончил')], help_text='Выберите статус', max_length=50, verbose_name='Статус контента')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенты',
            },
        ),
    ]
