# Generated by Django 3.2.16 on 2024-03-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('IN STOCK', 'В наличии'), ('OUT', 'Закончилось')], max_length=50, verbose_name='Наличие')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('data_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('data_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('image', models.FileField(upload_to='merchs/media/image/', verbose_name='Изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя амбассадора')),
                ('cost', models.FloatField(verbose_name='Цена товара')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='MerchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch_merch', to='merch.merch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch_merch', to='merch.order')),
            ],
        ),
    ]
