# Generated by Django 3.2.16 on 2024-03-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchorder',
            name='unique_merch_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='merch',
            new_name='merchs',
        ),
        migrations.AlterUniqueTogether(
            name='merchorder',
            unique_together={('merch', 'order')},
        ),
    ]
