# Generated by Django 3.2.16 on 2024-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='size_foot',
            field=models.PositiveIntegerField(default=None, verbose_name='Размер обуви, см'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size_shirt',
            field=models.PositiveIntegerField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], verbose_name='Размер одежды'),
        ),
    ]
