# Generated by Django 3.2.16 on 2024-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='image/', verbose_name='Изображения'),
        ),
    ]
