# Generated by Django 3.2.16 on 2024-03-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20240304_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='size_shirt',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество товара'),
        ),
    ]
