# Generated by Django 3.2.16 on 2024-03-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_auto_20240304_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='merchorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchorder', to='merch.order', verbose_name='Амбассадор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоймость'),
        ),
    ]
