# Generated by Django 3.2.16 on 2024-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_auto_20240305_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merch',
            field=models.ManyToManyField(related_name='merchs', through='merch.MerchOrder', to='merch.Merch', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size_foot',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Размер обуви, см'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size_shirt',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, null=True, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество товара'),
        ),
        migrations.AddConstraint(
            model_name='merchorder',
            constraint=models.UniqueConstraint(fields=('merch', 'order'), name='unique_merch_order'),
        ),
    ]
