# Generated by Django 3.2.16 on 2024-03-09 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='other',
            field=models.CharField(max_length=255, null=True, verbose_name='Цель обучения (другое)'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='comments',
            field=models.TextField(max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='education',
            field=models.CharField(max_length=255, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='work',
            field=models.CharField(max_length=255, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_end',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'))], verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.RegexValidator(regex='^[A-Z0-9]+$')], verbose_name='Промокод'),
        ),
    ]
