# Generated by Django 3.2.16 on 2024-03-09 20:27

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0002_auto_20240309_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='Амбассадор прошел Онбординг'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='completed_guide',
            field=models.BooleanField(default=False, verbose_name='Амбассадор выполнил задания из Гайда'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_end',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 3, 9, 20, 27, 39, 575652, tzinfo=utc))], verbose_name='Дата окончания'),
        ),
    ]
