# Generated by Django 3.2.16 on 2024-03-09 21:09

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0003_auto_20240310_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassador',
            old_name='completed_guide',
            new_name='guide',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='completed_onboarding',
            new_name='onboarding',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_end',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 3, 9, 21, 9, 17, 868333, tzinfo=utc))], verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
