# Generated by Django 3.2.16 on 2024-03-10 08:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contents_guide'),
        ('ambassadors', '0004_auto_20240310_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador', to='content.contents', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цель обучения (другое)'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='social',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_end',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 3, 10, 8, 49, 20, 793532, tzinfo=utc))], verbose_name='Дата окончания действия'),
        ),
    ]
